### ISSUE TITLE
quand je paste une ligne samarchpa

### ISSUE THREAD

**Issue by Delthas** [emersion/mdrgpalu#15]
salu ^^

quand je fais ctrl x pour cut une ligne puis ctrl v il se passe rien
fin ça cut mais ça paste pas après^^
pareil pr ctrl c, si je ctrl v il se apsse rien XD

salut ^^

**Comment by emersion** [comment]
Duplicate of #16

**Comment by Delthas** [comment]
nn là ça crash pa ça fait rien juste c différent
pck là c ligne pa sélection
